// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBlogPostReducer from "../add_blog_post_reducer";
import DeleteBlogPostReducer from "../delete_blog_post_reducer";
import UpdateBlogPostReducer from "../update_blog_post_reducer";

export type AddBlogPostParams = __Infer<typeof AddBlogPostReducer>;
export type DeleteBlogPostParams = __Infer<typeof DeleteBlogPostReducer>;
export type UpdateBlogPostParams = __Infer<typeof UpdateBlogPostReducer>;

